# TESTING
#
# This compose file is meant to be used for testing the application (say for
# reviewing someones branch) as it will deploy both the FE and BE with the
# proxy, however it does not maintain a volume for the DB data -- BUT does
# provide access to the db via Adminer
#

version: '3.1'

services:

  db:
    build: ./db
    restart: always
    networks:
      - mynetwork

  adminer:
    image: adminer
    restart: always
    networks:
      - mynetwork
    ports:
      - "8080:8080"
  
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile.deploy
    depends_on: 
      - db
    restart: always
    networks:
      - mynetwork
    ports:
      - "8080"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app

  client:
    build: ./client
    depends_on: 
      - app
    restart: always
    networks:
      - mynetwork

  proxy:
    build: ./proxy
    depends_on: 
      - client
    restart: always
    networks:
      - mynetwork
    ports:
      - "80:80"

networks:
  mynetwork:
