version: '3.1'

services:

  db:
    build: ./db
    image: clinic-mysql
    restart: always
    networks:
      - mynetwork
  
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile.deploy
    depends_on: 
      - db
    restart: always
    networks:
      - mynetwork
    ports:
      - "8080"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app

  client:
    build: ./client
    depends_on: 
      - app
    restart: always
    networks:
      - mynetwork

  proxy:
    build: ./proxy
    depends_on: 
      - client
    restart: always
    networks:
      - mynetwork
    ports:
      - "80:80"

networks:
  mynetwork:
