version: '3.1'

services:

  db:
    build: ./db
    image: clinic-mysql
    restart: always
    networks:
      - mynetwork


  adminer:
    image: adminer
    restart: always
    networks:
      - mynetwork
    ports:
      - "8080:8080"
    
  
  app:
    build: ./app
    depends_on:
      - adminer
      - db
    networks:
      - mynetwork
    ports:
      - "5050:5000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app

networks:
  mynetwork:
