version: '3.1'

services:

  db:
    build: ./db
    image: clinic-mysql
    restart: always
    networks:
      - mynetwork
  
  app:
    build: ./app
    depends_on:
      - db
    networks:
      - mynetwork
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app

  proxy:
    build: ./proxy
    depends_on:
      - app
    networks:
      - mynetwork
    ports:
      - "80:80"

networks:
  mynetwork:
