export const mockData = [
  [
    "Adaptive Behaviour Assessment System",
    "Adult Form",
    "Adaptive Functioning",
    "Form",
    "16-89",
    "ABAS-2",
    "C",
    2,
  ],
  [
    "Eating Disorder Inventory",
    "Professional Manual",
    "Eating Disorder",
    "Manual",
    "16-89",
    "ABAS-2",
    "C",
    2,
  ],
  [
    "Draw a Person",
    "Scoring Chart",
    "Projective",
    "Book",
    "16-89",
    "ABAS-2",
    "C",
    2,
  ],
  [
    "Adaptive Behaviour Assessment System",
    "Adult Form",
    "Adaptive Functioning",
    "Form",
    "16-89",
    "ABAS-2",
    "C",
    2,
  ],
];
