# Use root/example as user/password credentials

version: '3.1'

services:

  db:
    image: clinic-mysql
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
